store/my_app/urls.py
#URLconf

#to call a view (in views.py), we need to map it to a URL
from django.conf.urls import patterns, url
import views


urlpatterns = patterns('',
    url(r'^$', views.HomepageView.as_view(), name='homepage'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^accountitemlist', views.AccountItemsView.as_view(), name='account_items'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='account_detail'),


#    url(r'^detail', views.DetailView.as_view(), name='detail')
)

store/store_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'store_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^my_app/', include('my_app.urls', namespace="my_app")),

)

store/my_app/models.py
from django.db import models
import datetime


class AccountID(models.Model):
    date_created = models.DateTimeField(default=datetime.datetime.today())

    def __str__(self):
        return str(self.date_created)


class CompanyInfo(models.Model):
    account_id = models.ForeignKey(AccountID)
    company_name = models.CharField(max_length=200, default=' ', null=True)
    company_url = models.CharField(max_length=50, default=' ', null=True)

    def __str__(self):
        return self.company_name


class AccountName(models.Model):
    account_id = models.ForeignKey(AccountID)
    first_name = models.CharField(max_length=50, default=' ', null=True)
    last_name = models.CharField(max_length=50, default=' ', null=True)
    email = models.CharField(max_length=75, default=' ', null=True)
    phone_number = models.CharField(max_length=10, default=' ', null=True)


class Address(models.Model):
    account_id = models.ForeignKey(AccountID)
    attention = models.CharField(max_length=50, default=' ', null=True)
    address_line1 = models.CharField(max_length=200, default=' ', null=True)
    address_line2 = models.CharField(max_length=200, default=' ', null=True)
    city = models.CharField(max_length=50, default=' ', null=True)
    state = models.CharField(max_length=2, default="NY", null=True)
    zipcode = models.CharField(max_length=5, default=' ', null=True)
    country = models.CharField(max_length=50, default="US")
    is_billing = models.BooleanField(default=False)
    #is_ship_to = models.BooleanField(default=False)


class Service(models.Model):
    service_name = models.CharField(max_length=200, default=' ', null=True)
    service_description = models.TextField(max_length=400, default=' ', null=True)
    service_price = models.FloatField(max_length=8, default=' ', null=True)

    def __str__(self):
        return self.service_name


#    def get_description(self):
 #       return self.service_description

#    def _get_service_info(self):
 #       return '%s %s' % (self.service_description, self.service_price)
#
 #   service_info = property(_get_service_info)

    class Meta:
        ordering = ["id"]


class Order(models.Model):
    account_id = models.ForeignKey(AccountID)
    service_name = models.ForeignKey(Service, null=True)
    service_date = models.DateField(default=datetime.date.today())
    service_time = models.TimeField(default=datetime.time)
    is_gift = models.BooleanField(default=False)

store/my_app/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone #ADDED IN 9TH MODIFICATION
from django.http import HttpResponse    #ADDED THIS
from django.template import RequestContext, loader #ADDED IN 2nd MODIFICATION
from django.shortcuts import render     #ADDED IN 3rd MODIFICATION
from django.http import Http404         #ADDED IN 4th MODIFICATION
from django.shortcuts import get_object_or_404, render #ADDED IN 5TH MODIFICATION
from django.shortcuts import get_object_or_404  #ADDED IN 6TH MODIFICATION
from django.http import HttpResponseRedirect    #ADDED IN 6TH MODIFICATION
from django.core.urlresolvers import reverse    #ADDED IN 6TH MODIFICATION

from django.views import generic
from models import Service, AccountID, AccountName, Address, CompanyInfo, Order

from itertools import chain     #used to make multiple querysets in one view


class HomepageView(generic.ListView):
    template_name = 'my_app/homepage.html'
    context_object_name = 'list_of_services'

    def get_queryset(self):
        return Service.objects.all()


class DetailView(generic.DetailView):
    model = Service
    template_name = 'my_app/detail.html'


    def get_queryset(self):
        return Service.objects.all()


class AccountItemsView(generic.ListView):
    template_name = 'my_app/account_items.html'
    context_object_name = 'account_item_list'



    def get_queryset(self):
        accountname_list = AccountName.objects.all()
        companyinfo_list = CompanyInfo.objects.all()
        address_list = Address.objects.all()
        order_list = Order.objects.all()
  #      return AccountID.objects.all()
        #return AccountName.objects.all() + Address.objects.all()
        combine_list = list(chain(accountname_list, companyinfo_list, address_list, order_list))
        return combine_list

class NewUserDetailView(generic.DetailView):
    template_name = 'my_app/new_user.html'
    context_object_name = 'user_list'



    def get_queryset(self):
        accountname_list = AccountName.objects.all()
        companyinfo_list = CompanyInfo.objects.all()
        address_list = Address.objects.all()
        order_list = Order.objects.all()
        combine_list = list(chain(accountname_list, companyinfo_list, address_list, order_list))
        return combine_list

store/my_app/templates/my_app/account_detail.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

store/my_app/templates/my_app/account_items.html
{% if account_item_list %}
    <ul>
    {% for item in account_item_list %}
        <li><a href="{% url 'my_app:account_detail' item.id %}">{{ item.last_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No account items are available.</p>
{% endif %}

store/my_app/templates/my_app/detail.html
<h1>{{ service.service_name }}</h1>
<h2>{{ service.service_description }}</h2>
<h3>{{ service.service_price }}</h3>

store/my_app/templates/my_app/home.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Lab Helpers</title>
     <link rel="stylesheet" href="home.css">
</head>
<body>


<h1> <img src="emc24.png" alt="E=mc^2 image" width="40px" height="25px"> Lab Helpers </h1>

<form>
	<fieldset>
		<legend>LABS:</legend>
		<ul>
			<li>
				<p class="lab_names">lab name</p>
			</li>
		</ul>
	</fieldset>
	
	<br>
	<br>
	
	<fieldset>
		<legend>PRACTICE PROBLEMS:</legend>
		<ul>
			<li><p class="lab_names">practice problems name</p></li>
		</ul>
	</fieldset>
</form>

<br>
<br>

<button type="button" onclick="alert('Hello World!')">Leave a comment</button>

</body>
</html>

store/my_app/templates/my_app/homepage.html
{% if list_of_services %}
    <ul>
    {% for service in list_of_services %}
        <li><a href="{% url 'my_app:detail' service.id %}">{{service.service_name}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No services are available.</p>
{% endif %}

store/my_app/templates/my_app/lab_detail.html
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Lab Helpers</title>
     <link rel="stylesheet" href="lab_detail.css">
</head>
<body>
<div class="header"> <img src="emc24.png" alt="E=mc^2 image" width="40px" height="25px"> Lab Helpers </div>
<div class="subheader">  Lab Number: Lab Name </div>

<table>
  <caption>Grades</caption>
  <tr>
    <th>Topic 1</th>
    <th>Topic 2</th>		
    <th>Topic 3</th>
    <th>Topic 4</th>		
    <th>Total</th>
  </tr>
  <tr>
    <td>grade1</td>
    <td>grade2</td>		
    <td>grade3</td>
    <td>grade4</td>		
    <td>Total</td>
  </tr>
</table>

<form>
	<div class="question-body">
	<p class="topic">Topic Name</p>
	<ol>
		<li>
			<p class="question">Question Text</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice1"> Choice 1</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice2"> Choice 2</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice3"> Choice 3</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice4"> Choice 4</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice5"> Choice 5</p>
		</li>
		
		<br>
		
		<li>
			<p class="question">Question Text</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice1"> Choice 1</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice2"> Choice 2</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice3"> Choice 3</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice4"> Choice 4</p>
			<p id="choice"><input type="radio" name="multiple_choice_options" value="choice5"> Choice 5</p>		
		</li>
	</ol>
	</div>
	<br>
	<br>
<p id="button"><input type="submit" value="Submit"></p>
</form>

store/my_app/templates/my_app/new_user.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<form>


<fieldset>
<legend>LAA:</legend>

First name:<br>
<input type="text" name="firstname" value="Mickey">
<br>
Last name:<br>
<input type="text" name="lastname" value="Mouse">

    <input type="radio" name="sex" value="male" checked>Male
<br>
<input type="radio" name="sex" value="female">Female

    <select name="cars">
<option value="volvo">Volvo</option>
<option value="saab">Saab</option>
<option value="fiat">Fiat</option>
<option value="audi">Audi</option>
</select>

    <textarea name="message" rows="10" cols="30">
The cat was playing in the garden.
</textarea>

    <button type="button" onclick="alert('Hello World!')">Click Me!</button>


    <input list="browsers">
<datalist id="browsers">
  <option value="Internet Explorer">
  <option value="Firefox">
  <option value="Chrome">
  <option value="Opera">
  <option value="Safari">
</datalist>

    User name:<br>
<input type="text" name="username">
<br>
User password:<br>
<input type="password" name="psw">

    <input type="checkbox" name="vehicle" value="Bike">I have a bike
<br>
<input type="checkbox" name="vehicle" value="Car">I have a car

    Quantity (between 1 and 5):
  <input type="number" name="quantity" min="1" max="5">

     Birthday:
  <input type="date" name="bday">

    Enter a date before 1980-01-01:
  <input type="date" name="bday" max="1979-12-31"><br>
  Enter a date after 2000-01-01:
  <input type="date" name="bday" min="2000-01-02"><br>

     Select your favorite color:
  <input type="color" name="favcolor">

      <input type="range" name="points" min="0" max="10">

     Birthday (month and year):
  <input type="month" name="bdaymonth">

    Select a week:
  <input type="week" name="week_year">


     Select a time:
  <input type="time" name="usr_time">

    Birthday (date and time):
  <input type="datetime" name="bdaytime">

    Birthday (date and time):
  <input type="datetime-local" name="bdaytime">

    E-mail:
  <input type="email" name="email">

     Search Google:
  <input type="search" name="googlesearch">

     Telephone:
  <input type="tel" name="usrtel">

    Add your homepage:
  <input type="url" name="homepage">

    <!-- value specifies the initial value of an input field-->
    c value="John">
<br>
Last name:<br>
<input type="text" name="lastname">


    First name:<br>
<input type="text" name="firstname" value="John" readonly>
<br>
Last name:<br>
<input type="text" name="lastname">


    First name:<br>
<input type="text" name="firstname" value="John" disabled>
<br>
Last name:<br>
<input type="text" name="lastname">


    First name:<br>
<input type="text" name="firstname" value="John" size="40">
<br>
Last name:<br>
<input type="text" name="lastname">


    First name:<br>
<input type="text" name="firstname" maxlength="10">

    <!--The autofocus attribute is a boolean attribute.

When present, it specifies that an <input> element should automatically get focus when the page loads.-->
    First name:<input type="text" name="fname" autofocus>

    <!--
    The height and width attributes specify the height and width of an <input> element.

The height and width attributes are only used with <input type="image">.
-->
    <input type="image" src="img_submit.gif" alt="Submit" width="48" height="48">


<!--
The list attribute refers to a <datalist> element that contains pre-defined options for an <input> element.
-->
    <input list="browsers">

<datalist id="browsers">
  <option value="Internet Explorer">
  <option value="Firefox">
  <option value="Chrome">
  <option value="Opera">
  <option value="Safari">
</datalist>


    <!--
    The min and max attributes specify the minimum and maximum value for an <input> element.

The min and max attributes work with the following input types: number, range, date, datetime, datetime-local, month, time and week.
-->

    Enter a date before 1980-01-01:
<input type="date" name="bday" max="1979-12-31">

Enter a date after 2000-01-01:
<input type="date" name="bday" min="2000-01-02">

Quantity (between 1 and 5):
<input type="number" name="quantity" min="1" max="5">


    <!--
    The multiple attribute is a boolean attribute.

When present, it specifies that the user is allowed to enter more than one value in the <input> element.

The multiple attribute works with the following input types: email, and file.

A file upload field that accepts multiple values:
-->

    Select images: <input type="file" name="img" multiple>


    <!--
    The pattern attribute specifies a regular expression that the <input> element's value is checked against.

The pattern attribute works with the following input types: text, search, url, tel, email, and password.

Tip: Use the global title attribute to describe the pattern to help the user.

Tip: Learn more about regular expressions in our JavaScript tutorial.

An input field that can contain only three letters (no numbers or special characters):
-->

    Country code: <input type="text" name="country_code" pattern="[A-Za-z]{3}" title="Three letter country code">

   <!--

    The placeholder attribute specifies a hint that describes the expected value of an input field (a sample value or a short description of the format).

The hint is displayed in the input field before the user enters a value.

The placeholder attribute works with the following input types: text, search, url, tel, email, and password.

-->

<input type="text" name="fname" placeholder="First name">


<!--
The required attribute is a boolean attribute.

When present, it specifies that an input field must be filled out before submitting the form.

The required attribute works with the following input types: text, search, url, tel, email, password, date pickers, number, checkbox, radio, and file.

-->

Username: <input type="text" name="usrname" required>


<!--
The step attribute specifies the legal number intervals for an <input> element.

Example: if step="3", legal numbers could be -3, 0, 3, 6, etc.

Tip: The step attribute can be used together with the max and min attributes to create a range of legal values.

The step attribute works with the following input types: number, range, date, datetime, datetime-local, month, time and week.

-->

<input type="number" name="points" step="3">



    <br><br>
<input type="submit" value="Submit">
</fieldset>
</form>

</body>
</html>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id=choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice"{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>


{% if list_of_services %}
    <ul>
    {% for service in list_of_services %}
        <li><a href="{% url 'my_app:detail' service.id %}">{{service.service_name}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No services are available.</p>
{% endif %}

 account_id = models.ForeignKey(AccountID)
    company_name = models.CharField(max_length=200, default=' ', null=True)
    company_url =
first_name = models.CharField(max_length=50, default=' ', null=True)
    last_name = models.CharField(max_length=50, default=' ', null=True)
    email = models.CharField(max_length=75, default=' ', null=True)
    phone_number = models.CharField(max_length
attention = models.CharField(max_length=50, default=' ', null=True)
    address_line1 = models.CharField(max_length=200, default=' ', null=True)
    address_line2 = models.CharField(max_length=200, default=' ', null=True)
    city = models.CharField(max_length=50, default=' ', null=True)
    state = models.CharField(max_length=2, default="NY", null=True)
    zipcode = models.CharField(max_length=5, default=' ', null=True)
    country = models.CharField(max_length=50, default="US")
    is_billing = models.BooleanField(default=False)